---
version: latest
build: DEBUG
target: X64
---
ACPI:
  SSDT-HV-DEV: "ACPI/SSDT-HV-DEV.dsl"
  SSDT-HV-VMBUS: "ACPI/SSDT-HV-VMBUS.dsl"
  # Этот SSDT должен загружаться после SSDT-HV-DEV
  SSDT-HV-PLUG: "ACPI/SSDT-HV-PLUG.dsl"
Drivers:
  - HfsPlus
@ifdef(RELEASE)
  - OpenCanopy
@endif
  - OpenPartitionDxe
  - OpenRuntime
  - ResetNvramEntry
Kexts:
  Lilu: latest
  VirtualSMC: latest
  # Основной kext поддержки Hyper-V для macOS 12.0 и новее.
  MacHyperVSupportMonterey:
    specifier: "*"
    properties:
      MinKernel: "21.0.0"
  # Основной kext поддержки Hyper-V для macOS 10.4 до 11.0.
  MacHyperVSupport:
    specifier: latest
    properties:
      MaxKernel: "20.99.99"
  # Синтетический графический драйвер (для Gen2 VM)
  # - Этот kext по умолчанию отключён, так как OpenCore не может инъектировать его.
  # - Требует установки в /Library/Extensions (или /System/Library/Extensions)
  #   с отключённой подписью kext в SIP на macOS 11 (Big Sur) и новее.
  MacHyperVFramebuffer:
    specifier: "*"
Tools:
  # Также известен как UEFIShell
  - OpenShell
