## @file
# Файл патчей конфигурации config.plist для запуска macOS на Hyper-V
#
# Copyright (c)2021-2025, Goldfish64. All rights reserved.
# Copyright (c)2023-2025, Cory Bennett. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

# Этот файл расширяет существующие значения по умолчанию из OCE-Build и MacHyperVSupport.
# @see https://github.com/Qonfused/OCE-Build/blob/main/docs/resources/base-config.yml
# @see https://github.com/acidanthera/MacHyperVSupport/blob/master/README.md

# Ссылки на ресурсы для более подробной информации о разумных настройках по умолчанию:
# - https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf
# (или https://dortania.github.io/docs/latest/Configuration.html)

#region: Base Configuration - Keep in sync with docs/resources/base-config.yml

################################################################################
# Косметические исправления #
################################################################################

# Удалить предупреждающие комментарии
@delete('#WARNING -1', '#WARNING -2', '#WARNING -3', '#WARNING -4')
# Удалить избыточный комментарий
@delete('NVRAM.Add.7C436110-AB2A-4BBB-A880-FE41995C9F82.#INFO (prev-lang:kbd)')

@ifdef(RELEASE)
# Использовать тему GoldenGate по умолчанию с OpenCanopy.
# - https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html
Misc:
 Boot:
 PickerMode: String | "External"
 PickerVariant: String | "Acidanthera\GoldenGate"
@endif

# Изменяет язык установщика/клавиатуры macOS по умолчанию на английский.
# - Список поддерживаемых языков можно найти по ссылке (HEX -> ASCI):
# https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/AppleKeyboardLayouts/AppleKeyboardLayouts.txt
NVRAM:
 Add:
7C436110-AB2A-4BBB-A880-FE41995C9F82:
 prev-lang:kbd: String | "en-US:0"

################################################################################
# Платформа (SMBIOS) исправления #
################################################################################

# Требуется для macOS Tahoe, поскольку iMac19,1 (2019, Coffee Lake+) был удалён.
PlatformInfo:
 Generic:
 SystemProductName: String | "iMac20,1"

# Предотвращает инъекцию SMBIOS в не-apple ОС.
#
# Этот подход с UpdateSMBIOSMode откладывает обновления SMBIOS до macOS, чтобы
# избежать конфликтов с активацией лицензии Windows OEM и другим OEM ПО.
#
# Это работает путем записи информации SMBIOS в другую область таблицы SMBIOS,
# которая не читается Windows, и вместо этого патчит macOS AppleSmbios.kext для чтения
# из нового места. Оригинальная область SMBIOS остаётся нетронутой.
#
# - Note1: Все ACPI инъекции, патчи, удаления по-прежнему применяются OpenCore
# при использовании этого метода. Чтобы предотвратить любое ACPI воздействие,
# лучше загружаться через Windows Boot Manager.
#
# - Note2: Активация Windows OEM потенциально проблемна только для лицензий
# без привязанных аккаунтов Windows.
#
# - Note3: Это может сломать совместимость Bootcamp на Windows. Можно вернуть
# функциональность (в ущерб некоторому OEM ПО на hackintosh), используя
# ниже указанные значения OpenCore по умолчанию:
#
# Kernel.Quirks.CustomSMBIOSGuid: Boolean | false
# PlatformInfo.UpdateSMBIOSMode: String | "Create"
Kernel:
 Quirks:
 CustomSMBIOSGuid: Boolean | true
PlatformInfo:
 UpdateSMBIOSMode: String | "Custom"

################################################################################

@ifdef(DEBUG)
# Отладочные режимы (рекомендуются для DEBUG версии OpenCore)
# - https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html
# - https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/kernel-debugging.html#nvram
Kernel:
 Quirks:
 PanicNoKextDump: Boolean | true
 PowerTimeoutKernelPanic: Boolean | true
Misc:
 Debug:
 AppleDebug: Boolean | true
 ApplePanic: Boolean | true
 DisableWatchDog: Boolean | true
 Target: Number |67
NVRAM:
 Add:
7C436110-AB2A-4BBB-A880-FE41995C9F82:
 # Разбор используемых boot-аргументов:
 # `-v` (verbose режим)
 # `debug=0x100` (маска отладки; отключает watchdog чтобы избежать перезагрузки при панике)
 # `keepsyms=1` (показывает отладочные символы в логе panic)
 # `msgbuf=1048576` (увеличивает буфер сообщений ядра до1 МБ; избегает усечения)
 boot-args: String | "-v debug=0x100 keepsyms=1 msgbuf=1048576"
@endif

################################################################################
# Косметические исправления Plist #
################################################################################

# Очищаем значения по умолчанию в Sample.plist
ACPI:
 @override
 Delete: Array | []
Booter:
 @override
 MmioWhitelist: Array | []
 @override
 Patch: Array | []
Kernel:
 @override
 Block: Array | []
 @override
 Force: Array | []
 @override
 Patch: Array | []
Misc:
 @override
 Entries: Array | []
UEFI:
 @override
 ReservedMemory: Array | []

#endregion

################################################################################
# Исправления, связанные с ACPI #
################################################################################

ACPI:
 @override
 Patch:
 # Дополнение к SSDT-HV-VMBUS
 - Base: String | "_SB.VMOD"
 Comment: String | "_HID to XHID rename (Hyper-V VMOD)"
 Count: Number |1
 Find: Data | <5F484944>
 Replace: Data | <58484944>
 TableSignature: Data | <44534454>
 - Base: String | "_SB.VMOD.VMBS"
 Comment: String | "_HID to XHID rename (Hyper-V VMBus)"
 Count: Number |1
 Find: Data | <5F484944>
 Replace: Data | <58484944>
 TableSignature: Data | <44534454>
 # Дополнение к SSDT-HV-DEV
 - Base: String | "_SB.VMOD.TPM2"
 Comment: String | "_STA to XSTA rename (Hyper-V TPM)"
 Count: Number |1
 Find: Data | <5F535441>
 Replace: Data | <58535441>
 TableSignature: Data | <44534454>
 - Base: String | "_SB.NVDR"
 Comment: String | "_STA to XSTA rename (Hyper-V NVDIMM)"
 Count: Number |1
 Find: Data | <5F535441>
 Replace: Data | <58535441>
 TableSignature: Data | <44534454>
 - Base: String | "_SB.EPC"
 Comment: String | "_STA to XSTA rename (Hyper-V EPC)"
 Count: Number |1
 Find: Data | <5F535441>
 Replace: Data | <58535441>
 TableSignature: Data | <44534454>
 - Base: String | "_SB.VMOD.BAT1"
 Comment: String | "_STA to XSTA rename (Hyper-V battery)"
 Count: Number |1
 Find: Data | <5F535441>
 Replace: Data | <58535441>
 TableSignature: Data | <44534454>

################################################################################
# Исправления BIOS/прошивки #
################################################################################

Booter:
 Quirks:
 AvoidRuntimeDefrag: Boolean | true
 ProvideCustomSlide: Boolean | true

################################################################################
# Исправления загрузки #
################################################################################

Kernel:
 Quirks:
 # Предоставляет корректные значения TSC и FSB ядру, а также отключает
 # проверку топологии CPU (10.8+)
 ProvideCurrentCpuInfo: Boolean | true

UEFI:
 APFS:
 # Отключает минимальную версию APFS для записей загрузчика для Catalina и старее.
 MinDate: Number | -1
 MinVersion: Number | -1
 Output:
 # Устанавливает масштабирование дисплея для boot picker + логирования отладки.
 UIScale: Number | -1
 Quirks:
 # Требуется для Windows Server2019 / Windows10 и новее
 DisableSecurityPolicy: Boolean | true

################################################################################
# Исправления графики #
################################################################################

Kernel:
 Add:
 # Переопределяет Kernel.Add для MacHyperVFramebuffer.
 @override(BundlePath)
 - BundlePath: String | "MacHyperVFramebuffer.kext"
 Comment: String | "Должен быть установлен в /Library/Extensions или /System/Library/Extensions для полной функциональности."
 Enabled: Boolean | false
 Force:
 # Требуется при загрузке MacHyperVFramebuffer из /Library/Extensions.
 # - При загрузке из /Library/Extensions в macOS11 (Big Sur) и новее,
 # требуется отключение подписи kext. Используйте `csr-active-config`.
 # - Если загружать из /System/Library/Extensions, этот патч не обязателен,
 # но SIP (защита файловой системы и подпись kext) должны быть отключены.
 - Arch: String | "Any"
 BundlePath: String | "System/Library/Extensions/IOGraphicsFamily.kext"
 ExecutablePath: String | "IOGraphicsFamily"
 Identifier: String | "com.apple.iokit.IOGraphicsFamily"
 PlistPath: String | "Info.plist"
 Enabled: Boolean | false

################################################################################
# Исправления безопасности #
################################################################################

Misc:
 Security:
 # Разрешает устанавливать запись загрузки по умолчанию при удержании CTRL.
 AllowSetDefault: Boolean | true
 # Показывать все типы загрузочных разделов в boot picker.
 # - https://dortania.github.io/OpenCore-Post-Install/universal/security/scanpolicy.html
 ScanPolicy: Number |0
 # Модель Apple Secure Boot и политика
 SecureBootModel: String | "Disabled"
 # Конфигурация OpenCore vault (optional=no vault enforced, insecure)
 Vault: String | "Optional"
NVRAM:
 Add:
7C436110-AB2A-4BBB-A880-FE41995C9F82:
 # Включает настройку System Integrity Protection (SIP) в macOS.
 #
 # По умолчанию мы отключаем подписывание kext (0x1) для MacHyperVFramebuffer;
 # требуется для macOS11 (Big Sur) и новее.
 #
 # - Возможные значения:
 # -00000000: По умолчанию (включено)
 # -01000000: Отключает подпись Kext
 # -02000000: Отключает защиту файловой системы
 # -03000000: Отключает и подпись kext, и защиту файловой системы
 # -67000000: Отключает все защиты SIP
 # - FF030000: Отключает все флаги в macOS High Sierra
 # - FF070000: Отключает все флаги в macOS Mojave и Catalina
 # - FF0F0000: Отключает все флаги в macOS Big Sur
 # - @see https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip
 csr-active-config: Data | <03000000>
NVRAM:
 Delete:
7C436110-AB2A-4BBB-A880-FE41995C9F82:
 # Переопределяет значение SIP в macOS.
 - csr-active-config

################################################################################
# Исправления VMApple/2 iCloud #
################################################################################

# Обход для обнаружения VM в macOS15
# - Этот патч изменяет значение hv_vmm_present чтобы обойти новые изменения VMApple,
# добавленные в Sequoia (часто ломают службы iCloud).
# - Тестировалось на macOS14 (Sonoma,23.0.0+) и macOS15 (Sequoia,24.0.0+).
# - Вы можете проверить работу патча командой:
# sysctl kern | grep 'kern.hv_vmm_present'
# Ожидаемый вывод:
# kern.hv_vmm_present:0
Kernel:
 Patch:
 - Arch: String | "x86_64"
 Comment: string | "Patch kern.hv_vmm_present=0 (macOS11+)"
 Identifier: String | "kernel"
 Find: Data | <68696265726E61746568696472656164790068696265726E617465636F756E7400>
 MinKernel: String | "20.4.0"
 Replace: Data | <68696265726E61746568696472656164790068765F766D6D5F70726573656E7400>
 - Arch: String | "x86_64"
 Comment: string | "Patch kern.hv_vmm_present=0 (macOS13+)"
 Identifier: String | "kernel"
 Find: Data | <626F6F742073657373696F6E20555549440068765F766D6D5F70726573656E7400>
 MinKernel: String | "22.0.0"
 Replace: Data | <626F6F742073657373696F6E20555549440068696265726E617465636F756E7400>
